In [62]:
def is_even(x):
    x = int(input("Write down a integer"))
    if is_numeric(8):
        if type(x)==int and x//2==0:
            print("This number is even")
        else:
            print("This number is")
    else:
        print("Please write numeric number")
        

In [63]:
is_even(8)

Write down a integer8


NameError: name 'is_numeric' is not defined

In [3]:
def is_even(x:int):
    if x%2==0:
        print(f"{x} is even")
    else:
        print(f"{x} is odd")

In [4]:
is_even(8)

8 is even


In [120]:
def reverse_vowels(x:str):
    ls_v = []
    ls_k = []
    word = dict(enumerate(x)) 
    for i,k in zip(word.keys(),word.values()):
        if k in ['a','e','i','o','u']:
            ls_v.append(k)
            ls_k.append(i)
    for  n,m in zip(ls_k,ls_v[::-1]):
         word[n]=m
    return ''.join(list(word.values()))     

    
            
        

In [121]:
reverse_vowels('hello')

'holle'

In [91]:
[i for i,k in zip({0: 'a', 1: 'l', 2: 'i'}.keys(),{0: 'a', 1: 'l', 2: 'i'}.values())]

[0, 1, 2]

In [90]:
list({0: 'a', 1: 'l', 2: 'i'}.keys())

[0, 1, 2]

In [75]:
dict(enumerate("ali"))

{0: 'a', 1: 'l', 2: 'i'}

In [71]:
en

In [ ]:
def reverse_vowels(x:str):
    enumarate(list(x))

In [6]:
x ='hello'

In [7]:
 y = x[:]

In [8]:
y

'hello'

In [9]:
 ls = []
for i in y:
        if i in ['a','e','i','o','u']:
            ls.append(i)
            ls_1 = ls[:]
print(ls_1)

['e', 'o']


In [10]:
ls.reverse()
print(ls)

['o', 'e']


In [11]:
for i,k in zip(ls_1,ls):
    print(i,k)

e o
o e


In [12]:
ls

['o', 'e']

In [13]:
ls_1

['e', 'o']

In [14]:
for i,k in zip(ls_1,ls):
    x.replace(i,k)
    print(x)

hello
hello


In [15]:
reverse_vowels('hello')

In [16]:
lst = ['e','o']
lst.reverse()

In [17]:
lst

['o', 'e']

In [18]:
x= 1
type(x)==int

True

In [19]:
2+2

4

In [20]:
'ali'

'ali'

In [21]:
person = {
    'name':'John',
    "age" : 30 ,
    "city" : "New York"
}

In [22]:
person['name']

'John'

In [23]:
person['job'] = 'ds'

In [24]:
person['job']

'ds'

In [25]:
del person['job']

In [26]:
person

{'name': 'John', 'age': 30, 'city': 'New York'}

In [28]:
list1 = [1,2,3]

In [29]:
list2 = list1

In [30]:
list1 == list2

True

In [31]:
list2 == list1

True

In [34]:
x = 5
y = 10

In [35]:
temp = x 

In [36]:
x = y 

In [37]:
y = temp

In [38]:
print(x,y)

10 5


In [39]:
x= 5
y = 10

In [40]:
x,y = y, x 
print(x,y)

10 5


In [47]:
x = 117

In [48]:
ls = list(range(int(x/2)+1))
ls.append(x)

In [52]:
ls.pop(0)

0

In [53]:
ls

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 117]

In [123]:
def factorial(x):
    if x==0 or x==1:
        return 1
    return x*factorial(x-1)

In [124]:
factorial(5)

120

In [54]:
list1 = []
for i in ls:
    if x%i==0:
        list1.append(i)a
        
    print(f'{x} is a prime number')
else:
    print(f'{x} is not a prime number')

117 is not a prime number


NameError: name 'factorial' is not defined

In [65]:
try:
    x = int(input("Enter a number : "))
except :
    print('Please enter a integer')

Enter a number : a
Please enter a integer


In [129]:
def factorial(x:int)->int:
    y = 1
    
    if x<0:
        print("Negative numbers do not have factorial")
    if x == 0 : 
        print(f"Factorial {x} is 1")
    else:
        for i in range(1,x+1):
            y*=i
    return y
            
        

In [132]:
factorial(0)

Factorial 0 is 1


1

In [137]:
def factorial(x):
    y= 1
    if x<0:
        print('No factorial value')
    else:
        for i in range(1,x+1):
            y*=(i)
    return y        

In [138]:
factorial(5)

120

In [66]:
import random

In [70]:
int(random.random()*10)

9

In [72]:
random.randint(1,1000)

517

In [78]:
random.randrange(0,1000,2)

678

In [81]:
numlist = random.sample(range(0,100),7)

In [82]:
numlist

[99, 86, 92, 1, 95, 35, 75]

In [84]:
count = 0
ls = [0,1]
while count <8:
    x = ls[-1]+ls[-2]
    ls.append(x)
    count +=1
    
print(ls)

[0, 1, 1, 2, 3, 5, 8, 13, 21, 34]


In [ ]:
""""
Q3. Write a code snippet to reverse a string.
Ans. Here, we have reversed a string without using any in-built function.
""""

In [85]:
str1  = "Analytic Geometry"

In [87]:
"".join(list(str1)[::-1])

'yrtemoeG citylanA'

In [88]:
x = "abckcba"

In [91]:
import math

In [92]:
math.ceil(len(x)/2)

4

In [93]:
math.floor(len(x)/2)

3

In [118]:
if len(x)%2==0:
    if x[:len(x)/2] == x[len(x)/2:]:
        print(f'{x} is a polindrome')
    else:
        print(f'{x} is not a polindrome')
else:
    if x[:math.floor(len(x)/2)]==x[:math.floor(len(x)/2):-1]:
        print(f'{x} is a polindrome')
    else:
        print(f'{x} is not a polindrome')
                           
                    
              

abckcba is a polindrome


In [112]:
x[math.ceil(len(x)/2)::-1]

'ckcba'

In [102]:
-1*math.floor(len(x))

-7

In [106]:
math.floor(len(x)/2)

3

In [110]:
math.ceil(len(x)/2)

4

In [113]:
math.ceil(len(x)/2)

4

In [ ]:
x[:3:-1]

In [124]:
with open('abc.txt','w') as f:
    pass
    

In [126]:
with open('xyz.txt','w') as f:
    f.write('script')
f.close()

In [127]:
with open('xyz.txt','r') as f:
    x= f.read()
    print(x)
f.close()

script


In [120]:
import os

In [127]:
f.close()

In [1]:
os.remove('xyz.txt')

<IPython.core.display.Javascript object>

In [129]:
os.system('abc.txt')

1

In [3]:
list1 = [1,1,2,3,4,5,6]

In [ ]:
list1 = 

In [ ]:
#prime number icin 2 den basla karkok +1 icin butun sayilara bol eger kalan sifir veren varsa prime degil
#kaln sifir veren yoksa prime


In [4]:
from functools import reduce

reduce(lambda x, y: x if x < y else y, [5,7,3,4,5,6,])

3

In [10]:
dellist = [5,7,3,4,5,6,1]

In [11]:
del dellist[0]

In [12]:
dellist

[7, 3, 4, 5, 6, 1]

In [14]:
list1

AttributeError: 'list' object has no attribute 'max'

In [15]:
max(list1)

6

In [16]:
min(list1)

1

In [17]:
min([5,7,3,4,5,6,])

3

In [18]:
dic = {"x":3,"y":4,"z":5,"t":10}

In [20]:
min(dic.values())

3

In [26]:
tup = ((0,1,2,3),(4,5,6,7),(8,9,10))

In [27]:
sum([y for i in tup for y in i])/len([y for i in tup for y in i])

5.0

In [25]:
[y for i in tup for y in i]

[0, 1, 2, 3, 4, 5, 6, 8, 9, 10]

In [ ]:
#Check palindrome

In [1]:
def is_palindrome(string):
    
    reverse_string = string[::-1]
    return reverse_string == string
                        

In [2]:
word = "madam"

In [3]:
if is_palindrome(word):
    print( word,"is palindrome")
else : 
    print(word, "is not a palindroeme")
    

madam is palindrome


In [ ]:
#write a programe to find th efactoriual of a number

In [16]:
def factorial(x:int):
    value=1
    if x <0:
        print('Negative number has no facorial values')
    elif x==0:
        print(f"Factorial of {x} = 1")
    else:
        while 1<=x:
            value *=x
            x=(x-1)
    return value
        
        

In [17]:
factorial(5)

120

In [18]:
def factorial(n):
    if n==0:
        return 1
    else:
        return n*factorial(n-1)

In [19]:
factorial(5)

120

In [ ]:
#def find_largest number in a list

In [22]:
def find_largest(numbers):
    largest = numbers[0]
    for  num in numbers:
        if num >largest:
                largest= num
    return largest

In [23]:
find_largest([1,2,3,4,5,6,4,6,2,8,2,10])

10

In [ ]:
largest = numbers[0]
for num in numbers:
    if num>largest:
        largest = num
return largest

In [ ]:
#Write a program to calculate frequency of number in a list

In [33]:
def freq(liste:list):
    
    return {i: str(liste.count(i))+' Adet' for i in set(liste)}
        
        
        

In [34]:
freq([1,1,1,1,4,5,6,6,6,7,8,8,8,8,10])

{1: '4 Adet',
 4: '1 Adet',
 5: '1 Adet',
 6: '3 Adet',
 7: '1 Adet',
 8: '4 Adet',
 10: '1 Adet'}

In [28]:
for i in set([1,1,1,1,4,5,6,6,6,7,8,8,8,8,10]):
    print(i)

1
4
5
6
7
8
10


In [54]:
def prime(x:int):
    for i in range(2,int(x**0.5)+1):
        if x<2:
            return False
        elif x%i!=0:
            return True
        elif x%i==0:
            return False
   
        

In [55]:
num = 27 
if prime(num):
    print(num, ' is a prime')
else:
    print(num,' is not a prime')

27  is a prime


In [41]:
prime(27)

27  is prime
27 is not a prime
27  is prime
27  is prime


In [35]:
27**0.5

5.196152422706632

In [43]:
list(range(2,int(27**0.5)+1))

[2, 3, 4, 5]

In [128]:
def is_prime(x):
    if x<2:
        return False
    for i in range(2,int(x**0.5)+1):
        if x%i==0:
            return False
    return True   

In [129]:
is_prime(11)

True

In [140]:
def is_prime(x):
    if x<2:
        return False
    for i in range(2,int(x**0.5)+1):
        if x%i==0:
            return False
    return True

num = 19
if is_prime(num):
    print(num,' is prime')
else:
    print(num,' is not a prime')

19  is prime


In [130]:
set([1,2,3,5,2,0])&set([1,15,6,0])

{0, 1}

In [141]:
def common(list1,list2):
    return set([i for i in list1 if i in list2]) 
        

In [143]:
common([1,2,3,4,5,6,7],[10,2,4,6])

{2, 4, 6}

In [168]:
def second_largest(x):
    new_list = []
    
   
    while len(new_list)<3:
        largest = x[0]
        for i in x:
            if i>largest:
                largest = i
        x.remove(largest)
        new_list.append(largest)
        
 
    return new_list[1]  
            
        

In [169]:
second_largest([1,2,3,4,5,6,7,8,9])

8

In [170]:
import numpy
def uni(list1):
    return numpy.unique(list1)

In [171]:
uni([1,1,1,2,3,4,5,5,6,7,6,])

array([1, 2, 3, 4, 5, 6, 7])

In [173]:
list(set([1,1,1,2,3,4,5,5,6,7,6,]))

[1, 2, 3, 4, 5, 6, 7]

In [1]:
import decimal

In [3]:
decimal.Decimal(10)

Decimal('10')

In [6]:
fib = [0,1]

In [7]:
for i in range(5):
    fib.append(fib[-1]+fib[-2])
print(fib)

[0, 1, 1, 2, 3, 5, 8]


In [13]:
list1 = [1,2,3]
list1.append([3,4,5])
list1

[1, 2, 3, [3, 4, 5]]

In [15]:
list1 = [1,2,3]
list1.extend([3,4,5])
list1

[1, 2, 3, 3, 4, 5]

In [16]:
"Pro g r amm  ing".count(' ')

5

In [17]:
string = "Python is 1 "

In [18]:
import re

In [21]:
re.sub("[^0-9]","",string)

'1'

In [22]:
re.sub("[^A-Za-z]","",string)

'Pythonis'

In [26]:
re.findall("[\s]",string)

[' ', ' ', ' ']

In [27]:
string.replace(" ","")

'Pythonis1'

In [28]:
from random import shuffle

In [33]:
list1 = ['ali','veli','elli']

In [34]:
shuffle(list1)

In [35]:
list1

['veli', 'ali', 'elli']

In [55]:
def this_prime(x):
    if x<2:
        return False
    for i in range(2,int(x**0.5)+1):
        if x%i==0:
            return False
    return True

num = 20

        

In [56]:
def first_n(n):
    
    first_n = []
    while len(first_n)<n+1:
        for i in range(n**2):
            if this_prime(i):
                first_n.append(i)
    return first_n[:5]   


In [57]:
first_n(5)

[2, 3, 5, 7, 11]

In [14]:
class MyMath:
    def __init__(self,name,surname,job,salary):
        self.name = name
        self.surname = surname
        self.job = job
        self.salary = salary
    
    def fullname(self):
        print(f"{self.name+' '+ self.surname}")

In [15]:
my = MyMath('Ali','Veli','Teacher','2000')

In [16]:
my.fullname()

Ali Veli


In [17]:
my.__dict__

{'name': 'Ali', 'surname': 'Veli', 'job': 'Teacher', 'salary': '2000'}

In [31]:
class Employee:
    """Employee Class : name, surname, pay"""
    
    raise_amount = 1.2
    
    def __init__(self, name, surname, pay):
        self.name = name
        self.surname = surname
        self.pay = pay
        
    def fullname(self):
        print(f"{self.name+' '+self.surname}")
        
    def pay_raised(self):
        
        print(f"pay raise is  : {int(self.pay)*Employee.raise_amount}")
        

In [32]:
employ = Employee('Ali','Veli','2000')

In [33]:
employ.pay_raised()

pay raise is  : 2400.0


In [34]:
employ.raise_amount

1.2

In [35]:
employ.pay

'2000'

In [36]:
employ.pay_raised()

pay raise is  : 2400.0


In [37]:
bolunen = 10
x
bolen = 0

try:
    bolum=bolunen/bolen
except ZeroDivisionError:
    print("Hata")
    

NameError: name 'x' is not defined

In [40]:


try:
    bolunen = 10
    x
    bolen = 0
    bolum=bolunen/bolen
except ZeroDivisionError:
    print("Hata")
    
except NameError:
    print("Tanimlanamayan Degisken")

Tanimlanamayan Degisken


In [42]:
[i.upper()for  i in ['Ali','veli','kIrk']]

['ALI', 'VELI', 'KIRK']

In [45]:
while True:
    try:
        sayi=int(input("sayi"))
        print("girdiginiz sayi : ",sayi)
    except Exception as e:
        print('Lutfen gecerli bir sayi giriniz')
        print("Hata: ",e)
    else:
        print("program cikiliyor")
        break
        

sayi5
girdiginiz sayi :  5
program cikiliyor
sayi6
girdiginiz sayi :  6
program cikiliyor
sayi7
girdiginiz sayi :  7
program cikiliyor


KeyboardInterrupt: Interrupted by user

In [47]:
while True:
    try:
        sayi = int(input("sayi:"))
        print("girdiginiz sayi:", sayi)
    except Exception as e:
        print("Lutfen gecerli bir numerik deger giriniz")
        print("Hata: ",e)
    else:
        print("programdan cikiliyor")
        break
    finally:
        print('fina')

sayi:ali
Lutfen gecerli bir numerik deger giriniz
Hata:  invalid literal for int() with base 10: 'ali'
fina
fina


KeyboardInterrupt: Interrupted by user

In [48]:
count = 0 
while True:
    
    try:
        sayi = int(input("sayi:"))
        print("girdiginiz sayi : ",sayi)
    except Exception as e:
        print("Numerik dege giriniz")
        print("Hata",e)
        count +=1
        if count > 3:
            print("too many failed input")
            break
    else:
        print("else calisti programdan cikiliyor")
        break

sayi:ali
Numerik dege giriniz
Hata invalid literal for int() with base 10: 'ali'
sayi:5
girdiginiz sayi :  5
else calisti programdan cikiliyor


In [49]:
import os

In [50]:
os.listdir()

['.ipynb_checkpoints', 'Practice.ipynb', 'Py-TaskScheduler']

In [52]:
f = open('Advantage of python.txt', mode = "w")

In [53]:
f.close()

In [54]:
f.read()

ValueError: I/O operation on closed file.

In [ ]:
with open('Advantage of python.txt',mode = 'w')

In [55]:
f.open()

AttributeError: '_io.TextIOWrapper' object has no attribute 'open'

In [68]:
with open('Advantage of python.txt',mode = 'w') as f:
    f.write('text15')
with open('Advantage of python.txt',mode = 'r') as f:
    print(f.read())
    f.close()

text15


ValueError: I/O operation on closed file.

In [74]:
with open('Advantage of python.txt',mode = 'w+') as f:
    f.write('text90')
    x = f.read()
print(x)


In [70]:
f.read()

ValueError: I/O operation on closed file.

In [12]:
class Dog:
    def __init__(self,name,age):
        self.name = name
        self.age = age
        
    def __str__(self):
        return f"{self.name} is {self.age} years old"

In [13]:
dog = Dog('gumus',"3")

In [14]:
print(dog)

gumus is 3 years old


In [ ]:
#Numpy

In [16]:
import numpy as np

In [17]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [20]:
a = np.zeros(10)

In [21]:
a[4]=1

In [22]:
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [23]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [25]:
np.arange(50)

0

In [27]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [30]:
np.arange(10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
#find inidces of non zero


In [33]:
np.nonzero([1,0,0,5,0,0,3])

AttributeError: 'tuple' object has no attribute 'argmax'

In [35]:
np.where(np.array([1,0,0,5,0,0,3]) != 0)

(array([0, 3, 6], dtype=int64),)

In [42]:
np.random.randint(0,100,16).reshape(2,2,2,2)

array([[[[59, 87],
         [ 5,  7]],

        [[33, 97],
         [40, 55]]],


       [[[89, 43],
         [66,  6]],

        [[29, 46],
         [71, 17]]]])

In [47]:
np.random.random(10).mean()

0.2789542191248706

In [52]:
a = np.ones(25).reshape(5,5)
a[1:-1,1:-1]=0
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [55]:
np.array([0,1]*4)
np.array([1,0]*4)

array([1, 0, 1, 0, 1, 0, 1, 0])

In [56]:
count=0
ls = []
while count<4:
    ls.extend(np.array([0,1]*4))
    ls.extend(np.array([1,0]*4))
    count +=1
np.array(ls).reshape(8,8)
    
    

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [63]:
a = np.zeros(64).reshape(8,8)
a[0::2,1::2]=int(1)
a[1::2,0::2]=int(1)
a.astype(int)

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [70]:
np.tile(np.array([[1,2],[1,2]]),(2,2))

array([[1, 2, 1, 2],
       [1, 2, 1, 2],
       [1, 2, 1, 2],
       [1, 2, 1, 2]])

In [73]:
np.array([[1,2],[1,2]]).shape

(2, 2)

In [74]:
np.array([[1,2],[1,2]])

array([[1, 2],
       [1, 2]])

In [76]:
np.unravel_index(99, (6,7,8))

(1, 5, 3)

In [81]:
np.linspace(0,1,13,endpoint =False)[1:]

array([0.07692308, 0.15384615, 0.23076923, 0.30769231, 0.38461538,
       0.46153846, 0.53846154, 0.61538462, 0.69230769, 0.76923077,
       0.84615385, 0.92307692])

In [85]:
a = np.random.random(10)
a.sort()

In [86]:
a

array([0.19457448, 0.20020032, 0.47300456, 0.51436997, 0.5144228 ,
       0.52457039, 0.59078347, 0.74344822, 0.83896915, 0.97300906])

In [96]:
np.random.randint(0,1000,10)

array([837, 713,  94,  19, 698, 456, 525, 685, 618, 890])

In [97]:
np.random.randint(1,3,3)

array([1, 1, 2])

In [98]:
np.random.randint(1,3,3)

array([1, 2, 2])

In [108]:
a = np.random.random(10)
print(a)
print(a.max())
a[a.argmax()]=0
print(a)

[0.6242131  0.48439105 0.29411112 0.28853053 0.02270928 0.9717221
 0.02734499 0.13693073 0.05477142 0.8421846 ]
0.9717221038052549
[0.6242131  0.48439105 0.29411112 0.28853053 0.02270928 0.
 0.02734499 0.13693073 0.05477142 0.8421846 ]


In [109]:
a = np.arange(25).reshape(5,5)

In [110]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [111]:
b = a.copy()

In [112]:
a[1,:] = b[3,:]
a[3,:] = b[1,:]


In [113]:
a

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]])

In [114]:
a[[1]]

array([[15, 16, 17, 18, 19]])

In [116]:
a =np.random.randint(0,10,10)

In [117]:
a

array([5, 8, 2, 7, 1, 3, 5, 9, 7, 8])

In [118]:
a = np.array([2, 0, 0, 4, 5, 2, 8, 4, 7, 0])

In [121]:
np.bincount(a)

array([3, 0, 2, 0, 2, 1, 0, 1, 1], dtype=int64)

In [131]:
bin(8)

'0b1000'

In [ ]:
#Decorator allow you activate or deactivate your function in your function it enchance the fuctionality

In [ ]:
#@ ile active oluyor 

#Decorator prensibi
@decorator
def ....

In [ ]:
#Degisken olarak fonksiyon


In [132]:
def deneme():
    print('abc')

In [ ]:
#function are able to assign tio variable, the way without call them
f= deneme #here we do not add ()

In [133]:
f =deneme

In [134]:
f()

abc


In [ ]:
#Founction inside function

In [137]:
def deneme():
    print("deneme fonklsiyonu claisyor")
    
    def test():
        return "test  fonsiyonu claisyor"
    
    print(test())

In [138]:
deneme()

deneme fonklsiyonu claisyor
test  fonsiyonu claisyor
